export const seleccion = (tema) => {
    const fondo = document.getElementById("fondo")
    const rango = document.getElementById("temaselec")
    const temar = document.getElementById("tema")
    const pantalla = document.getElementById("pantallita")
    const teclas = document.getElementById("teclas")
    const b1 = document.getElementById("b1")
    const b2 = document.getElementById("b2")
    const b3 = document.getElementById("b3")
    const b4 = document.getElementById("b4")
    const b5 = document.getElementById("b5")
    const b6 = document.getElementById("b6")
    const b7 = document.getElementById("b7")
    const b8 = document.getElementById("b8")
    const b9 = document.getElementById("b9")
    const b0 = document.getElementById("b0")
    const mas = document.getElementById("mas")
    const menos = document.getElementById("menos")
    const dividir = document.getElementById("dividir")
    const multiplicar = document.getElementById("multiplicar")
    const punto = document.getElementById("punto")
    const del = document.getElementById("del")
    const reset = document.getElementById("reset")
    const igual = document.getElementById("igual")

if(tema === 1){
    fondo.setAttribute("class", "temaf1")
    rango.setAttribute("class", "temar1")
    temar.setAttribute("class", "rango1")
    pantalla.setAttribute("class", "temap1")
    teclas.setAttribute("class", "temats1")
    b1.setAttribute("class","botonesop1")
    b2.setAttribute("class","botonesop1")
    b3.setAttribute("class","botonesop1")
    b4.setAttribute("class","botonesop1")
    b5.setAttribute("class","botonesop1")
    b6.setAttribute("class","botonesop1")
    b7.setAttribute("class","botonesop1")
    b8.setAttribute("class","botonesop1")
    b9.setAttribute("class","botonesop1")
    b0.setAttribute("class","botonesop1")
    mas.setAttribute("class","botonesop1")
    menos.setAttribute("class","botonesop1")
    dividir.setAttribute("class","botonesop1")
    multiplicar.setAttribute("class","botonesop1")
    punto.setAttribute("class","botonesop1")
    del.setAttribute("class","botones1")
    reset.setAttribute("class","botones1")
    igual.setAttribute("class","igual1")

}else if(tema === 2){
    fondo.setAttribute("class", "temaf2")
    rango.setAttribute("class", "temar2")
    temar.setAttribute("class", "rango2")
    pantalla.setAttribute("class", "temap2")
    teclas.setAttribute("class", "temats2")
    b1.setAttribute("class","botonesop2")
    b2.setAttribute("class","botonesop2")
    b3.setAttribute("class","botonesop2")
    b4.setAttribute("class","botonesop2")
    b5.setAttribute("class","botonesop2")
    b6.setAttribute("class","botonesop2")
    b7.setAttribute("class","botonesop2")
    b8.setAttribute("class","botonesop2")
    b9.setAttribute("class","botonesop2")
    b0.setAttribute("class","botonesop2")
    mas.setAttribute("class","botonesop2")
    menos.setAttribute("class","botonesop2")
    dividir.setAttribute("class","botonesop2")
    multiplicar.setAttribute("class","botonesop2")
    punto.setAttribute("class","botonesop2")
    del.setAttribute("class","botones2")
    reset.setAttribute("class","botones2")
    igual.setAttribute("class","igual2")
}else{
    fondo.setAttribute("class", "temaf3")
    rango.setAttribute("class", "temar3")
    temar.setAttribute("class", "rango3")
    pantalla.setAttribute("class", "temap3")
    teclas.setAttribute("class", "temats3")
    b1.setAttribute("class","botonesop3")
    b2.setAttribute("class","botonesop3")
    b3.setAttribute("class","botonesop3")
    b4.setAttribute("class","botonesop3")
    b5.setAttribute("class","botonesop3")
    b6.setAttribute("class","botonesop3")
    b7.setAttribute("class","botonesop3")
    b8.setAttribute("class","botonesop3")
    b9.setAttribute("class","botonesop3")
    b0.setAttribute("class","botonesop3")
    mas.setAttribute("class","botonesop3")
    menos.setAttribute("class","botonesop3")
    dividir.setAttribute("class","botonesop3")
    multiplicar.setAttribute("class","botonesop3")
    punto.setAttribute("class","botonesop3")
    del.setAttribute("class","botones3")
    reset.setAttribute("class","botones3")
    igual.setAttribute("class","igual3")
}
}

